---
- name: Linux Hardening Audit
  hosts: all
  gather_facts: false
  become: true

  vars:
    remote_script: /tmp/linux_hardening_audit.sh
    report_name: "hardening-{{ inventory_hostname }}.txt"

  tasks:

    - name: Copy audit script
      copy:
      src: files/linux_hardening_audit.sh
      dest: /tmp/linux_hardening_audit.sh
      mode: "0755"

    - name: Execute audit
      shell: "{{ remote_script }} /tmp/{{ report_name }}"
      register: audit_result
      changed_when: false

    - name: Show execution result
      debug:
        var: audit_result.stdout_lines

    - name: Display report
      shell: cat /tmp/{{ report_name }}
      register: report_output
      changed_when: false

    - debug:
        var: report_output.stdout_lines

    - name: Fetch report
      fetch:
        src: "/tmp/{{ report_name }}"
        dest: reports/
        flat: yes

    - name: Cleanup report
      file:
        path: "/tmp/{{ report_name }}"
        state: absent

    - name: Cleanup script
      file:
        path: "{{ remote_script }}"
        state: absent